package dev.jimmymorales.wordlex.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFa73900)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdbcd)
val md_theme_light_onPrimaryContainer = Color(0xFF380d00)
val md_theme_light_secondary = Color(0xFF77574b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdbcd)
val md_theme_light_onSecondaryContainer = Color(0xFF2c160d)
val md_theme_light_tertiary = Color(0xFF685e30)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf1e3a8)
val md_theme_light_onTertiaryContainer = Color(0xFF211b00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a18)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a18)
val md_theme_light_surfaceVariant = Color(0xFFf4ded6)
val md_theme_light_onSurfaceVariant = Color(0xFF52433e)
val md_theme_light_outline = Color(0xFF85736d)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeea)
val md_theme_light_inverseSurface = Color(0xFF362f2d)
val md_theme_light_inversePrimary = Color(0xFFffb596)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb596)
val md_theme_dark_onPrimary = Color(0xFF5b1b00)
val md_theme_dark_primaryContainer = Color(0xFF802a00)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdbcd)
val md_theme_dark_secondary = Color(0xFFe7beaf)
val md_theme_dark_onSecondary = Color(0xFF432a20)
val md_theme_dark_secondaryContainer = Color(0xFF5c4035)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdbcd)
val md_theme_dark_tertiary = Color(0xFFd4c78e)
val md_theme_dark_onTertiary = Color(0xFF383006)
val md_theme_dark_tertiaryContainer = Color(0xFF4f471a)
val md_theme_dark_onTertiaryContainer = Color(0xFFf1e3a8)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a18)
val md_theme_dark_onBackground = Color(0xFFede0dc)
val md_theme_dark_surface = Color(0xFF201a18)
val md_theme_dark_onSurface = Color(0xFFede0dc)
val md_theme_dark_surfaceVariant = Color(0xFF52433e)
val md_theme_dark_onSurfaceVariant = Color(0xFFd8c2ba)
val md_theme_dark_outline = Color(0xFFa08d86)
val md_theme_dark_inverseOnSurface = Color(0xFF201a18)
val md_theme_dark_inverseSurface = Color(0xFFede0dc)
val md_theme_dark_inversePrimary = Color(0xFFa73900)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFf36e33)
val error = Color(0xFFba1b1b)
val exactMatch = Color(0xFF5FA059)
val closeMatch = Color(0xFFC2AB4E)
